backend:
    name: github
    repo: sscaff1/dsc-website

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/index/index.md"
        label: "Index"
        name: "index"
        fields: 
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: Vision, name: vision, widget: markdown}
          - label: "Team Members"
            name: member
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Email, name: email, widget: string}
              - {label: Title, name: title, widget: string}
              - {label: Bio, name: bio, widget: markdown}
              - {label: Photo, name: photo, widget: image}
      