backend:
  name: github
  repo: sscaff1/dsc-website

media_folder: static/img
public_folder: /img

collections:
  - name: 'member'
    label: 'Team Members'
    folder: 'src/pages/members'
    create: true
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'member-section' }
      - { label: Name, name: name, widget: string }
      - { label: Email, name: email, widget: string, required: false }
      - { label: Title, name: title, widget: string }
      - { label: Bio, name: body, widget: markdown }
      - { label: Photo, name: photo, widget: image, required: false }
      - { label: Qualifications, name: qualifications, widget: string, required: false }
      - label: Education
        name: education
        widget: list
        fields:
          - { label: College, name: college, widget: string }
          - { label: Location, name: location, widget: string }
          - { label: Degree, name: degree, widget: string }
          - { label: Concentration, name: concentration, widget: string }
          - { label: Timeframe, name: timeframe, widget: string }
      - label: Awards
        name: awards
        widget: list
        required: false
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Timeframe, name: timeframe, widget: string }
      - label: Languages
        name: languages
        widget: list
        required: false
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Proficiency, name: proficiency, widget: string }

  - name: 'services'
    label: 'Services'
    folder: 'src/pages/services'
    create: true
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'service-section' }
      - { label: title, name: title, widget: string }
      - { label: description, name: body, widget: markdown }

  - name: projects
    label: 'Current Club Projects'
    folder: 'src/pages/projects'
    create: true
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'project-section' }
      - { label: title, name: title, widget: string }
      - { label: description, name: body, widget: markdown }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Vision'
        name: 'home'
        slug: '/'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'home-page' }
          - { label: Title, name: title, widget: hidden, default: Home }
          - { label: Vision, name: body, widget: markdown }
